apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: api1
  name: api1-controller
spec:
  replicas: 1
  selector:
    name: api1
  template:
    metadata:
      labels:
        name: api1
    spec:
      containers:
      - image: <your-docker-account>/<your-image-name>
        name: api1
        ports:
        - containerPort: 5000
          name: http-server

---

apiVersion: v1
kind: Service
metadata:
  name: api1
  labels:
    name: api1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    name: api1